Object.assign(window.NEZUMIMARU_TRANSLATIONS, {"これまでに描いた似顔絵の制作例です。":"Portraits I have created."});
Object.assign(window.NEZUMIMARU_TRANSLATIONS, {"制作で参加した受賞作品":"Award-winning collaborative work","2022年　Cluster GAMEJAM2022 テーマ賞受賞作品のワールド制作・バナーを担当":"2022 — World creation and banner design for a Theme Award-winning entry at Cluster GAMEJAM2022"});
Object.assign(window.NEZUMIMARU_TRANSLATIONS, {
  "ねずみのちょろりのイラスト": "Choroli illustration",
  "ねずみのちょろりのイラストを大きく見る": "View Choroli illustration larger",
  "NFTクリエイターズファイル「デジタルアート展」優秀賞": "NFT Creators File Digital Art Exhibition — Excellence Award",
  "EXPO2025 大阪・関西万博": "EXPO2025 Osaka, Kansai, Japan",
  "作品：": "Artwork: ",
  "受賞の紹介を見る": "Read the award announcement",
  "龍のおともだち": "A Dragon Friend",
  "龍のおともだちを大きく見る": "View A Dragon Friend larger",
  "入賞": "Selected Award",
  "第1回松本国際アート展示会「un do」展": "1st Matsumoto International Art Exhibition “un do”",
  "真紅の魂": "Crimson Soul",
  "真紅の魂を大きく見る": "View Crimson Soul larger",
  "ZIELCHAIN賞": "ZIELCHAIN Award",
  "天野喜孝 × ZIELCHAIN クリエイターコンテスト": "Yoshitaka Amano × ZIELCHAIN Creator Contest",
  "カレーをモチーフにしたキャラクター": "Curry-inspired character",
  "カレーをモチーフにしたキャラクターを大きく見る": "View Curry-inspired character larger",
  "第3位": "3rd Place",
  "神田カレーキャラクター選手権2023": "Kanda Curry Character Championship 2023",
  "夢見詩葉": "夢見詩葉",
  "夢見詩葉を大きく見る": "View 夢見詩葉 larger",
  "大阪賞": "Osaka Award",
  "Nコレ大阪": "N Collection Osaka",
  "MZDAOを紹介するPR漫画": "MZDAO promotional comic",
  "MZDAOを紹介するPR漫画を大きく見る": "View MZDAO promotional comic larger",
  "Twitter部門 最優秀賞": "Grand Prize — Twitter Category",
  "MZDAO PRコンテスト": "MZDAO PR Contest",
  "10/28–11/6": "10/28–11/6",
  "つくしのブックカバー展／枚方T-SITE 蔦屋書店（大阪）": "Tsukushi Book Cover Exhibition / Hirakata T-SITE Tsutaya Books, Osaka",
  "2/23–25": "2/23–25",
  "松本市立博物館（長野）": "Matsumoto City Museum, Nagano",
  "4/29–5/5": "4/29–5/5",
  "世田谷美術館（東京）": "Setagaya Art Museum, Tokyo",
  "6/7–7/2": "6/7–7/2",
  "江別蔦屋書店（北海道）": "Ebetsu Tsutaya Books, Hokkaido",
  "8/1–9/30": "8/1–9/30",
  "JR山手線 新橋駅（東京）": "JR Yamanote Line, Shimbashi Station, Tokyo",
  "10/1–11/30": "10/1–11/30",
  "JR山手線 原宿駅（東京）": "JR Yamanote Line, Harajuku Station, Tokyo",
  "11/30": "11/30",
  "イラスト作品集「CUT 2024」掲載": "Featured in the illustration art book CUT 2024",
  "12/1–翌1/30": "Dec 1–Jan 30 (following year)",
  "JR山手線 品川駅（東京）": "JR Yamanote Line, Shinagawa Station, Tokyo",
  "4月": "April",
  "渋谷PARCO（東京）": "Shibuya PARCO, Tokyo",
  "7/1–2": "7/1–2",
  "京セラドーム（大阪）": "Kyocera Dome, Osaka",
  "8/14〜": "8/14〜",
  "東京NFTアートキャラバン（上野）": "Tokyo NFT Art Caravan, Ueno",
  "9/16": "9/16",
  "和歌山城天守閣（和歌山）": "Wakayama Castle, Wakayama",
  "10/7": "10/7",
  "せんだいメディアテーク（宮城）": "Sendai Mediatheque, Miyagi",
  "12/9–10": "12/9–10",
  "ムーミンバレーパーク・メッツァビレッジ（埼玉）": "Moominvalley Park / Metsä Village, Saitama",
  "受賞作品と、展示のあゆみ。": "Award-winning art, and the places it has been.",
  "イラスト、キャラクター、PR漫画。作品と一緒に、これまでの受賞・展示・掲載をご紹介します。": "Explore illustration, character design and promotional comics through awards, exhibitions and publications.",
  "受賞・展示と作品": "Awards, Exhibitions & Art",
  "受賞・展示と作品｜ねずみまる 公式ホームページ": "Awards, Exhibitions & Art | Nezumimaru Official Website",
  "← 活動歴へ": "← Activity history",
  "受賞作品": "Award-winning works",
  "展示されたイラスト": "Exhibited illustration",
  "主な展示・掲載": "Selected exhibitions & publications",
  "画像をタッチすると、大きくご覧いただけます。": "Tap an image to view it larger.",
  "JR山手線に展示された、ちょろりのまちがいさがし": "Choroli spot-the-difference illustration exhibited on the JR Yamanote Line",
  "JR山手線に展示された、ちょろりのまちがいさがしを大きく見る": "View Choroli spot-the-difference illustration exhibited on the JR Yamanote Line larger",
  "駅で出会う、ちょろりたち。": "Meet Choroli and friends at the station.",
  "JR山手線の新橋駅・原宿駅・品川駅で展示されたイラスト。作品集「CUT 2024」にも掲載されています。": "An illustration exhibited at Shimbashi, Harajuku and Shinagawa stations on the JR Yamanote Line, also featured in the art book CUT 2024.",
  "ちょろりたちに会いにいく": "Meet Choroli and friends",
  "活動歴の一覧は、リットリンクでもご覧いただけます。": "The full activity history is also available on Lit.Link.",
  "リットリンクを見る": "Visit Lit.Link",
  "受賞作品と展示のあゆみを見る": "Explore award-winning works and exhibitions",
  "似顔絵のアルバム": "Portrait album",
  "アイコンや記念の一枚に。ちょろりたちと一緒の似顔絵も描いています。": "For profile icons and special memories, including portraits with Choroli and friends.",
  "お仕事姿の似顔絵": "Portrait at work",
  "お仕事姿の似顔絵を大きく見る": "View Portrait at work larger",
  "ふたりの似顔絵とちょろりたち": "A couple with Choroli and friends",
  "ふたりの似顔絵とちょろりたちを大きく見る": "View A couple with Choroli and friends larger",
  "ペットとちゃまる": "A pet with Chamaru",
  "ペットとちゃまるを大きく見る": "View A pet with Chamaru larger",
  "ピンクのキャラクターとちゃまる": "A pink character with Chamaru",
  "ピンクのキャラクターとちゃまるを大きく見る": "View A pink character with Chamaru larger",
  "人物アイコンとちゃまる": "Portrait icon with Chamaru",
  "人物アイコンとちゃまるを大きく見る": "View Portrait icon with Chamaru larger",
  "ちょろりたちといっしょに": "Together with Choroli and friends",
  "ちょろりたちといっしょにを大きく見る": "View Together with Choroli and friends larger",
  "笑顔の似顔絵": "A smiling portrait",
  "笑顔の似顔絵を大きく見る": "View A smiling portrait larger",
  "虹を背景にした似顔絵": "Portrait with a rainbow",
  "虹を背景にした似顔絵を大きく見る": "View Portrait with a rainbow larger",
  "紫色のお洋服の似顔絵": "Portrait in purple",
  "紫色のお洋服の似顔絵を大きく見る": "View Portrait in purple larger",
  "めがねの似顔絵とちゃまる": "Portrait with glasses and Chamaru",
  "めがねの似顔絵とちゃまるを大きく見る": "View Portrait with glasses and Chamaru larger",
  "ちょろりたちと、めがねの似顔絵": "Portrait with glasses and friends",
  "ちょろりたちと、めがねの似顔絵を大きく見る": "View Portrait with glasses and friends larger",
  "ピースの似顔絵": "Portrait with a peace sign",
  "ピースの似顔絵を大きく見る": "View Portrait with a peace sign larger",
  "ふたりの記念に": "A portrait for two",
  "ふたりの記念にを大きく見る": "View A portrait for two larger",
  "ちょろりたちと、男性の似顔絵": "A male portrait with Choroli and friends",
  "ちょろりたちと、男性の似顔絵を大きく見る": "View A male portrait with Choroli and friends larger",
  "巻き髪の似顔絵": "Portrait with curly hair",
  "巻き髪の似顔絵を大きく見る": "View Portrait with curly hair larger",
  "ちゃまると、女性の似顔絵": "A female portrait with Chamaru",
  "ちゃまると、女性の似顔絵を大きく見る": "View A female portrait with Chamaru larger",
  "やわらかなタッチの人物画": "A softly drawn portrait",
  "やわらかなタッチの人物画を大きく見る": "View A softly drawn portrait larger",
  "デフォルメした人物画": "A stylized portrait",
  "デフォルメした人物画を大きく見る": "View A stylized portrait larger",
  "イラストの制作例": "Illustration gallery",
  "人物やなかまたち、物語のある風景。いろいろなタッチのイラストをご紹介します。": "People, characters and scenes with a story — illustrations in a range of styles.",
  "街角を歩くイラスト": "An illustrated stroll through town",
  "街角を歩くイラストを大きく見る": "View An illustrated stroll through town larger",
  "装いを楽しむなかまたち": "Friends in distinctive outfits",
  "装いを楽しむなかまたちを大きく見る": "View Friends in distinctive outfits larger",
  "キャンプのひととき": "A camping moment",
  "キャンプのひとときを大きく見る": "View A camping moment larger",
  "絵を描く女の子": "A girl with her palette",
  "絵を描く女の子を大きく見る": "View A girl with her palette larger",
  "ストリートファイター6の非公式大会ファンイラスト": "Fan illustration for an unofficial Street Fighter 6 tournament",
  "ストリートファイター6の非公式大会ファンイラストを大きく見る": "View the fan illustration for an unofficial Street Fighter 6 tournament larger",
  "ゲームキャラクターのデフォルメ": "Stylized game characters",
  "ゲームキャラクターのデフォルメを大きく見る": "View Stylized game characters larger",
  "人物の全身イラスト": "A full-body character illustration",
  "人物の全身イラストを大きく見る": "View A full-body character illustration larger",
  "描く時間のイラスト": "The time spent drawing",
  "描く時間のイラストを大きく見る": "View The time spent drawing larger",
  "お仕事の様子を描いたイラスト": "An illustration of the creative process",
  "お仕事の様子を描いたイラストを大きく見る": "View An illustration of the creative process larger",
  "ありがとうのイラスト": "An illustrated thank-you",
  "ありがとうのイラストを大きく見る": "View An illustrated thank-you larger",
  "青い髪の女の子": "A blue-haired girl",
  "青い髪の女の子を大きく見る": "View A blue-haired girl larger",
  "いろいろなキャラクターたち": "More character designs",
  "姿や表情、色や衣装から、その子らしさを描きます。": "Bringing a character to life through shape, expression, color and costume.",
  "３人のデフォルメキャラクター": "Three stylized characters",
  "３人のデフォルメキャラクターを大きく見る": "View Three stylized characters larger",
  "ものがたりの女の子": "A storybook girl",
  "ものがたりの女の子を大きく見る": "View A storybook girl larger",
  "青い髪の男の子": "A blue-haired boy",
  "青い髪の男の子を大きく見る": "View A blue-haired boy larger",
  "色のバリエーション": "Color variations",
  "色のバリエーションを大きく見る": "View Color variations larger",
  "恐竜モチーフのなかまたち": "Dinosaur-inspired friends",
  "恐竜モチーフのなかまたちを大きく見る": "View Dinosaur-inspired friends larger",
  "箱のねこロボット": "A box-shaped cat robot",
  "箱のねこロボットを大きく見る": "View A box-shaped cat robot larger",
  "ねずみのロボット": "A mouse robot",
  "ねずみのロボットを大きく見る": "View A mouse robot larger",
  "絵画の風景と男の子": "A boy in a painted landscape",
  "絵画の風景と男の子を大きく見る": "View A boy in a painted landscape larger",
  "星空の絵画と女の子": "A girl in a painted starry sky",
  "星空の絵画と女の子を大きく見る": "View A girl in a painted starry sky larger",
  "髪色と表情のバリエーション": "Hair color and expression variations",
  "髪色と表情のバリエーションを大きく見る": "View Hair color and expression variations larger",
  "パーティーを楽しむ女の子": "A girl enjoying a party",
  "パーティーを楽しむ女の子を大きく見る": "View A girl enjoying a party larger",
  "機械の羽をもつキャラクター": "A character with mechanical wings",
  "機械の羽をもつキャラクターを大きく見る": "View A character with mechanical wings larger",
  "衣装で変わるキャラクター": "Character costume variations",
  "衣装で変わるキャラクターを大きく見る": "View Character costume variations larger",
  "花とお天気のなかまたち": "Flower and weather friends",
  "花をかぶった女の子": "A girl wearing a flower",
  "花をかぶった女の子を大きく見る": "View A girl wearing a flower larger",
  "花のなかまたち": "Flower friends",
  "花のなかまたちを大きく見る": "View Flower friends larger",
  "水色の花の女の子": "A girl with a pale blue flower",
  "水色の花の女の子を大きく見る": "View A girl with a pale blue flower larger",
  "かみなり雲の男の子": "A thundercloud boy",
  "かみなり雲の男の子を大きく見る": "View A thundercloud boy larger",
  "雨雲の男の子": "A raincloud boy",
  "雨雲の男の子を大きく見る": "View A raincloud boy larger",
  "ちょろりたちの、絵のアルバム。": "Choroli and friends: an art album.",
  "海のなかをのぞいて": "A peek under the sea",
  "海のなかをのぞいてを大きく見る": "View A peek under the sea larger",
  "窓のむこうの景色": "A view through the window",
  "窓のむこうの景色を大きく見る": "View A view through the window larger",
  "空の旅へ": "An adventure in the sky",
  "空の旅へを大きく見る": "View An adventure in the sky larger",
  "お誕生日のお祝い": "A birthday celebration",
  "お誕生日のお祝いを大きく見る": "View A birthday celebration larger",
  "ちょろりカフェ": "Choroli Cafe",
  "ちょろりカフェを大きく見る": "View Choroli Cafe larger",
  "ちょろりとクリスマスケーキ": "Choroli with a Christmas cake",
  "ちょろりとクリスマスケーキを大きく見る": "View Choroli with a Christmas cake larger",
  "ちゃまるとクリスマスのおやつ": "Chamaru with a Christmas treat",
  "ちゃまるとクリスマスのおやつを大きく見る": "View Chamaru with a Christmas treat larger",
  "ちゃまると甘いおやつ": "Chamaru with a sweet treat",
  "ちゃまると甘いおやつを大きく見る": "View Chamaru with a sweet treat larger",
  "ちょろりとチョコのおやつ": "Choroli with a chocolate treat",
  "ちょろりとチョコのおやつを大きく見る": "View Choroli with a chocolate treat larger",
  "お菓子のおうちのクリスマス": "Christmas at a gingerbread house",
  "お菓子のおうちのクリスマスを大きく見る": "View Christmas at a gingerbread house larger",
  "家族の物語": "A family story",
  "ビットコインを題材に、家族の時間を描いた全５枚の漫画です。": "A five-page comic about a family, with Bitcoin as a story theme.",
  "家族の物語 1枚目": "A family story — page 1",
  "家族の物語 1枚目を大きく見る": "View A family story — page 1 larger",
  "家族の物語 2枚目": "A family story — page 2",
  "家族の物語 2枚目を大きく見る": "View A family story — page 2 larger",
  "家族の物語 3枚目": "A family story — page 3",
  "家族の物語 3枚目を大きく見る": "View A family story — page 3 larger",
  "家族の物語 4枚目": "A family story — page 4",
  "家族の物語 4枚目を大きく見る": "View A family story — page 4 larger",
  "家族の物語 5枚目": "A family story — page 5",
  "家族の物語 5枚目を大きく見る": "View A family story — page 5 larger",
  "暮らしの気づきを、漫画に。": "Everyday observations in comics.",
  "交通安全の漫画": "A comic about road safety",
  "交通安全の漫画を大きく見る": "View A comic about road safety larger",
  "聞こえ方を描いたエッセイ漫画": "Essay comics about hearing",
  "日常の聞こえ方や感じたことを、エッセイ漫画にしています。": "Essay comics about everyday sounds and personal experiences.",
  "聞こえ方のエッセイ漫画 1枚目": "A comic about hearing — page 1",
  "聞こえ方のエッセイ漫画 1枚目を大きく見る": "View A comic about hearing — page 1 larger",
  "聞こえ方のエッセイ漫画 2枚目": "A comic about hearing — page 2",
  "聞こえ方のエッセイ漫画 2枚目を大きく見る": "View A comic about hearing — page 2 larger",
  "聞こえ方のエッセイ漫画 3枚目": "A comic about hearing — page 3",
  "聞こえ方のエッセイ漫画 3枚目を大きく見る": "View A comic about hearing — page 3 larger",
  "聞こえ方のエッセイ漫画 4枚目": "A comic about hearing — page 4",
  "聞こえ方のエッセイ漫画 4枚目を大きく見る": "View A comic about hearing — page 4 larger",
  "閉じる": "Close",
  "作品の拡大表示": "Enlarged artwork"
});

(() => {
  if (!('HTMLDialogElement' in window)) return;
  const viewer = document.createElement('dialog');
  viewer.className = 'art-viewer';
  viewer.setAttribute('aria-label', '作品の拡大表示');
  const bar = document.createElement('div');
  bar.className = 'art-viewer-header';
  const caption = document.createElement('p');
  caption.hidden = document.body.classList.contains('portrait-page');
  const close = document.createElement('button');
  close.type = 'button';
  close.textContent = '閉じる';
  const picture = document.createElement('img');
  bar.append(caption, close);
  viewer.append(bar, picture);
  document.body.append(viewer);
  let opener;
  close.addEventListener('click', () => viewer.close());
  viewer.addEventListener('click', event => {
    if (event.target !== viewer) return;
    const box = viewer.getBoundingClientRect();
    if (event.clientX < box.left || event.clientX > box.right || event.clientY < box.top || event.clientY > box.bottom) viewer.close();
  });
  viewer.addEventListener('close', () => { picture.removeAttribute('src'); opener?.focus(); });
  document.querySelectorAll('a.collection-zoom').forEach(link => {
    link.addEventListener('click', event => {
      if (event.button !== 0 || event.ctrlKey || event.metaKey || event.shiftKey || event.altKey) return;
      event.preventDefault();
      opener = link;
      const image = link.querySelector('img');
      picture.src = link.href;
      picture.alt = image.alt;
      caption.textContent = image.alt;
      viewer.classList.toggle('art-viewer-tall', Number(image.getAttribute('height')) > Number(image.getAttribute('width')) * 1.3);
      viewer.showModal();
      viewer.scrollTop = 0;
      close.focus();
    });
  });
})();
