Object.assign(window.NEZUMIMARU_TRANSLATIONS, {
  "イラスト／まちがいさがし": "Illustration / Puzzles",
  "← イラスト／まちがいさがしへ": "← Illustration / Puzzles",
  "← 漫画・ゲームへ": "← Comics & Game Art",
  "日々の発見を、親しみやすい物語に。": "Turning everyday discoveries into inviting stories.",
  "Xで50万回以上表示された旅行エッセイ漫画": "A travel comic with over 500,000 views on X",
  "丸ごと1匹たこやき食べた話": "The Takoyaki with a Whole Octopus Inside",
  "初めての大阪で出会った、ちょっとびっくりなたこやき。": "A surprising takoyaki discovery on my first trip to Osaka.",
  "旅先の小さな出来事を、全3枚のエッセイ漫画にしました。": "A small travel moment told in a three-page comic.",
  "Xでの表示回数": "Views on X",
  "万回": "× 10,000",
  "いいね": "Likes",
  "リポスト": "Reposts",
  "2023年9月11日の投稿／数値は2026年10月2日確認": "Posted September 11, 2023 · Metrics checked October 2, 2026",
  "Xでこの漫画を見る": "Read this comic on X",
  "PR漫画・SNS漫画・エッセイ漫画の制作も、お気軽にご相談ください。": "Get in touch about promotional, social media, or essay comics.",
  "その他の漫画作品": "More Comics",
  "漫画・ゲームの入口へ戻る": "Back to Comics & Game Art",
  "まちがいさがし制作": "Spot-the-Difference Illustration",
  "見つけて、笑顔になる。": "Find a difference. Find a smile.",
  "まちがいさがしのイラスト。": "Spot-the-difference illustrations.",
  "絵を眺める楽しさと、違いを見つける小さなわくわくを。": "Enjoy the illustrations and the little thrill of finding differences.",
  "2022年から続く、広報誌のお仕事": "An ongoing newsletter project since 2022",
  "猪狩工務店の広報誌": "Igari Construction’s Newsletter",
  "2022年から、猪狩工務店の広報誌に掲載するまちがいさがしを描いています。": "I have illustrated spot-the-difference puzzles for Igari Construction’s newsletter since 2022.",
  "節分、お花見、七夕、ハロウィン。季節の行事やなかまたちのしぐさを盛り込んだ作例をご紹介します。": "Explore seasonal illustrations for Setsubun, cherry blossom picnics, Tanabata, and Halloween.",
  "広報誌や会報、店舗のおたよりなど、媒体に合わせたまちがいさがしの制作をご相談いただけます。": "Commission puzzles tailored to company newsletters, community publications, or shop updates.",
  "まちがいさがしの制作を相談する": "Discuss a Puzzle Project",
  "料金の目安を見る": "View Pricing",
  "季節を楽しむ、制作例": "Seasonal Puzzle Illustrations",
  "節分": "Setsubun",
  "春のお花見": "Cherry Blossom Picnic",
  "七夕": "Tanabata",
  "ハロウィン": "Halloween",
  "鬼たちと楽しむ、にぎやかな節分。": "A lively Setsubun celebration with playful ogres.",
  "桜の下で、春を楽しむなかまたち。": "Friends enjoying spring beneath the cherry blossoms.",
  "星空と笹飾りに、願いをこめて。": "Wishes beneath the stars and decorated bamboo.",
  "かぼちゃやおばけと、秋のおまつり。": "An autumn celebration with pumpkins and ghosts.",
  "ちょろりたちとも、まちがいさがし。": "Play Spot the Difference with Choroli",
  "オリジナルキャラクター「ねずみのちょろり」のまちがいさがしも公開しています。": "You can also enjoy puzzles featuring my original character, Choroli the Mouse.",
  "ちょろりのまちがいさがしで遊ぶ": "Play Choroli’s Puzzles",
  "イラストと、まちがいさがし。": "Illustrations & Spot-the-Difference Puzzles",
  "季節のイラストや、広報誌のお仕事をご紹介します。": "Explore seasonal illustrations and newsletter commissions.",
  "広報誌のまちがいさがし": "Newsletter Spot-the-Difference Puzzles",
  "2022年から猪狩工務店の広報誌に掲載。季節に合わせた作例を専用ページにまとめました。": "Created for Igari Construction’s newsletter since 2022. Discover the seasonal examples on a dedicated page.",
  "まちがいさがしの制作例を見る": "Explore Puzzle Illustrations",
  "季節をめぐるイラスト": "Illustrations Through the Seasons",
  "旅行のエッセイや、日常を描く漫画。Xで50万回以上表示された作品も。": "Travel essays and everyday stories, including a comic with over 500,000 views on X.",
  "猪狩工務店 広報誌 2024年2月号": "Igari Construction Newsletter · February 2024",
  "猪狩工務店 広報誌 2024年2月号のまちがいさがし：節分": "Igari Construction Newsletter · February 2024 · Setsubun",
  "猪狩工務店 広報誌 2024年2月号のまちがいさがしを大きく見る（新しいタブ）": "Enlarge puzzle: Igari Construction Newsletter · February 2024 (new tab)",
  "猪狩工務店 広報誌 2024年4月号": "Igari Construction Newsletter · April 2024",
  "猪狩工務店 広報誌 2024年4月号のまちがいさがし：春のお花見": "Igari Construction Newsletter · April 2024 · Cherry Blossom Picnic",
  "猪狩工務店 広報誌 2024年4月号のまちがいさがしを大きく見る（新しいタブ）": "Enlarge puzzle: Igari Construction Newsletter · April 2024 (new tab)",
  "猪狩工務店 広報誌 2024年7月号": "Igari Construction Newsletter · July 2024",
  "猪狩工務店 広報誌 2024年7月号のまちがいさがし：七夕": "Igari Construction Newsletter · July 2024 · Tanabata",
  "猪狩工務店 広報誌 2024年7月号のまちがいさがしを大きく見る（新しいタブ）": "Enlarge puzzle: Igari Construction Newsletter · July 2024 (new tab)",
  "猪狩工務店 広報誌 2024年10月号": "Igari Construction Newsletter · October 2024",
  "猪狩工務店 広報誌 2024年10月号のまちがいさがし：ハロウィン": "Igari Construction Newsletter · October 2024 · Halloween",
  "猪狩工務店 広報誌 2024年10月号のまちがいさがしを大きく見る（新しいタブ）": "Enlarge puzzle: Igari Construction Newsletter · October 2024 (new tab)",
  "丸ごと1匹たこやき食べた話 1枚目": "The Takoyaki with a Whole Octopus Inside · Page 1",
  "たこやきの旅行エッセイ漫画 1枚目を大きく見る（新しいタブ）": "Enlarge takoyaki travel comic, page 1 (new tab)",
  "丸ごと1匹たこやき食べた話 2枚目": "The Takoyaki with a Whole Octopus Inside · Page 2",
  "たこやきの旅行エッセイ漫画 2枚目を大きく見る（新しいタブ）": "Enlarge takoyaki travel comic, page 2 (new tab)",
  "丸ごと1匹たこやき食べた話 3枚目": "The Takoyaki with a Whole Octopus Inside · Page 3",
  "たこやきの旅行エッセイ漫画 3枚目を大きく見る（新しいタブ）": "Enlarge takoyaki travel comic, page 3 (new tab)"
});
Object.assign(window.NEZUMIMARU_TRANSLATIONS, {"イラスト／まちがいさがし｜ねずみまる 公式ホームページ": "Illustration & Puzzles | Nezumimaru Official Website", "まちがいさがし制作｜ねずみまる 公式ホームページ": "Spot-the-Difference Illustration | Nezumimaru Official Website", "猪狩工務店の広報誌に描いた、春のお花見のまちがいさがし": "Cherry blossom picnic puzzle for Igari Construction’s newsletter", "春のお花見のまちがいさがしを大きく見る（新しいタブ）": "Enlarge the cherry blossom picnic puzzle (new tab)"});

Object.assign(window.NEZUMIMARU_TRANSLATIONS, {"まちがいさがしの拡大表示｜ねずみまる 公式ホームページ": "Spot-the-Difference Preview | Nezumimaru Official Website", "← まちがいさがしの制作例へ": "← Puzzle Illustrations", "まちがいさがしの制作例へ戻る": "Back to Puzzle Illustrations", "スマートフォンでは、ピンチ操作で拡大できます。": "On a phone, pinch to zoom in."});
